# Generated by Django 2.2 on 2019-04-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lastname', models.CharField(max_length=255)),
                ('Firstname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phoneNmuber', models.IntegerField()),
            ],
        ),
    ]
