# Generated by Django 2.2 on 2019-04-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('ItemID', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryId', models.IntegerField()),
                ('ProductName', models.CharField(max_length=255)),
                ('BrandName', models.CharField(max_length=255)),
                ('SellerID', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=11, max_digits=11)),
                ('Size', models.DecimalField(decimal_places=11, max_digits=11)),
                ('Color', models.CharField(max_length=255)),
                ('ProductImage_path', models.FileField(blank=True, null=True, upload_to='shop/')),
                ('Description', models.CharField(max_length=255)),
                ('SearchTerm', models.CharField(max_length=255)),
                ('Variations', models.CharField(max_length=255)),
            ],
        ),
    ]
